version: 2.1

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - run: xcodebuild -version

  build-machine:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
     - run: echo "on machine"

workflows:
  build-all:
    jobs:
      - build-docker
      - build-macos
      - build-machine