version: 2.1

orbs: 
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ruby/install:
          version: '2.6.3'
      - run: echo "Ruby 2.6.3 has been installed"

      
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build