version: 2.1

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - run: xcodebuild -version

workflows:
  build-all:
    jobs:
      - build-docker
      - build-macos