version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      
      - restore_cache:
          name: Restore Yarn Package Json Cache
          keys:
            - node-cache-{{ checksum "package.json" }}   
      
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      
      - save_cache:
          name: Save Yarn Package Json Cache
          key: node-cache-{{ checksum "package.json" }}  
          paths:
            - ~/.cache/yarn

workflows:
  cache-save-and-restore:
    jobs:
      - build