version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: echo "docker image"
  
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - run: xcodebuild -version

  build-machine:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
     - run: echo "on machine"
  
  build-windows: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  build-all:
    jobs:
      - build-docker
      - build-macos
      - build-machine
      - build-windows